#!/usr/bin/env python3
"""Register i18nstack skills and commands with Codex (OpenAI).

Codex discovers:
  - Skills: ~/.agents/skills/<name>/SKILL.md + agents/openai.yaml
  - Slash prompts: ~/.codex/prompts/<command>.md
"""

from __future__ import annotations

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

GENERATOR = "i18nstack/setup"
MARKER = ".codex-claude-source.json"
FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n?", re.DOTALL)
VALID_NAME_RE = re.compile(r"^[a-z0-9-]+$")
PROMPT_HEADER = f"<!-- Generated by {GENERATOR}"


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    slug = re.sub(r"-{2,}", "-", slug)
    return slug[:64].strip("-") or "imported"


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}, text
    body = text[match.end() :]
    meta: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip().strip("\"'")
        if key in {"name", "description", "argument-hint"}:
            meta[key] = value
    return meta, body


def clean_inline(value: str, fallback: str = "") -> str:
    value = re.sub(r"\s+", " ", value).strip()
    value = value.replace("<", "(").replace(">", ")")
    return value or fallback


def truncate(value: str, limit: int) -> str:
    if len(value) <= limit:
        return value
    return value[: limit - 3].rstrip() + "..."


def yaml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def title_from_slug(slug: str) -> str:
    return " ".join(
        part.upper() if part in {"db", "api", "ui", "nlp", "tdd", "mcp"} else part.capitalize()
        for part in slug.split("-")
    )


def first_heading_or_text(body: str, fallback: str) -> str:
    for line in body.splitlines():
        clean = line.strip().strip("#").strip()
        if clean and not clean.startswith("```"):
            return clean
    return fallback


def read_marker(path: Path) -> dict[str, Any] | None:
    marker = path / MARKER
    if not marker.is_file():
        return None
    try:
        data = json.loads(marker.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None
    return data if isinstance(data, dict) else None


def can_manage(target: Path) -> bool:
    if not target.exists():
        return True
    # Refresh any previously generated adapter (i18nstack or sync-claude-to-codex).
    # Skip only unmanaged dirs — likely a user-owned skill with the same name.
    return read_marker(target) is not None


def write_marker(target: Path, kind: str, source: Path) -> None:
    marker = {
        "generator": GENERATOR,
        "kind": kind,
        "source": str(source),
        "updatedAt": datetime.now(timezone.utc).isoformat(),
    }
    (target / MARKER).write_text(json.dumps(marker, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def compatibility_notes(source_kind: str) -> str:
    return f"""## Codex Compatibility

Installed by i18nstack `setup`. Re-run:

```bash
~/.codex/i18nstack/setup
```

(or the path where you cloned i18nstack).

When following the source {source_kind}:

1. Read the source file before acting.
2. Treat the source directory as the root for relative references, scripts, and assets.
3. Translate Claude tool names to Codex equivalents:
   - `Read`, `Edit`, `Write`, `MultiEdit`, `Glob`, `Grep`, `LS`, and `Bash` map to Codex filesystem and shell tools.
   - `TodoWrite` maps to `update_plan`.
   - `Task`, `Agent`, and named subagents map to Codex multi-agent tools when available; otherwise do the work in-thread.
   - `Skill(name)` and `$name` map to `$name` when that skill exists; otherwise read the matching skill under `~/.agents/skills/`.
   - `WebFetch` and `WebSearch` map to Codex browsing tools, with source citations when browsing is used.
4. Preserve safety instructions. Ask before destructive database, production, credential, deploy, or data-loss operations.
5. Ignore Claude-only frontmatter such as `allowed-tools` when it conflicts with the active Codex session policy.
"""


def register_skill(source_dir: Path, stack_dir: Path, codex_skills: Path, counts: dict[str, int]) -> None:
    source_file = source_dir / "SKILL.md"
    if not source_file.is_file():
        return

    frontmatter, body = parse_frontmatter(source_file.read_text(encoding="utf-8", errors="replace"))
    source_name = clean_inline(frontmatter.get("name", ""), source_dir.name)
    codex_name = source_dir.name if VALID_NAME_RE.match(source_dir.name) else slugify(source_name)
    target = codex_skills / codex_name

    if not can_manage(target):
        counts["skipped_skills"] += 1
        return

    original_desc = clean_inline(frontmatter.get("description", ""), first_heading_or_text(body, source_name))
    description = truncate(
        f"i18nstack skill for {source_name}. Use for ${codex_name} or tasks requiring: {original_desc}",
        1024,
    )

    target.mkdir(parents=True, exist_ok=True)
    (target / "SKILL.md").write_text(
        f"""---
name: {codex_name}
description: {yaml_string(description)}
---

# i18nstack Skill: {source_name}

Source: `{source_file}`

{compatibility_notes("skill")}
## Procedure

1. Read `{source_file}`.
2. Follow the source skill's workflow using Codex tools and the compatibility mapping above.
3. If the source skill references additional files under `{source_dir}`, read only the files needed for the current task.
""",
        encoding="utf-8",
    )
    agents = target / "agents"
    agents.mkdir(exist_ok=True)
    (agents / "openai.yaml").write_text(
        "interface:\n"
        f"  display_name: {yaml_string(title_from_slug(codex_name))}\n"
        f"  short_description: {yaml_string(truncate(f'i18nstack {source_dir.name}', 64))}\n"
        f"  default_prompt: {yaml_string(f'Use ${codex_name} for this i18n task.')}\n",
        encoding="utf-8",
    )
    write_marker(target, "skill", source_file)
    counts["skills"] += 1


def register_command(source_file: Path, stack_dir: Path, codex_skills: Path, codex_prompts: Path, counts: dict[str, int]) -> None:
    frontmatter, body = parse_frontmatter(source_file.read_text(encoding="utf-8", errors="replace"))
    command = slugify(source_file.stem)
    skill_target = codex_skills / command
    prompt_target = codex_prompts / f"{command}.md"

    if not can_manage(skill_target):
        counts["skipped_commands"] += 1
        return

    original_desc = clean_inline(frontmatter.get("description", ""), first_heading_or_text(body, f"/{command} command"))
    description = truncate(
        f"i18nstack slash command for /{command}. Use explicitly with ${command}: {original_desc}",
        1024,
    )

    skill_target.mkdir(parents=True, exist_ok=True)
    (skill_target / "SKILL.md").write_text(
        f"""---
name: {command}
description: {yaml_string(description)}
---

# i18nstack Command: /{command}

Source: `{source_file}`

{compatibility_notes("slash command")}
## Procedure

1. Read `{source_file}`.
2. Treat the user's invocation text after `/{command}` or `${command}` as the command arguments.
3. Apply placeholders as follows: `$ARGUMENTS` means all invocation arguments; `$1` through `$9` mean positional arguments.
4. Follow the imported command instructions using Codex tools and current-session permissions.
""",
        encoding="utf-8",
    )
    agents = skill_target / "agents"
    agents.mkdir(exist_ok=True)
    (agents / "openai.yaml").write_text(
        "interface:\n"
        f"  display_name: {yaml_string('/' + command)}\n"
        f"  short_description: {yaml_string(truncate(f'i18nstack /{command}', 64))}\n"
        f"  default_prompt: {yaml_string(f'Use ${command} with arguments for the /{command} workflow.')}\n"
        "policy:\n"
        "  allow_implicit_invocation: false\n",
        encoding="utf-8",
    )
    write_marker(skill_target, "command-skill", source_file)

    hint = clean_inline(frontmatter.get("argument-hint", ""))
    header = [
        "---",
        f"description: {yaml_string(truncate(original_desc, 300))}",
    ]
    if hint:
        header.append(f"argument-hint: {yaml_string(truncate(hint, 200))}")
    header.extend(
        [
            "---",
            "",
            f"{PROMPT_HEADER} from {source_file}. Re-run i18nstack setup instead of editing directly. -->",
            "",
            f"# Codex Prompt For i18nstack `/{command}`",
            "",
            f"The equivalent explicit skill adapter is `${command}`.",
            "",
            "## Imported Command",
            "",
        ]
    )
    prompt_target.write_text("\n".join(header) + body.lstrip(), encoding="utf-8")
    counts["commands"] += 1


def main() -> int:
    stack_dir = Path(sys.argv[1] if len(sys.argv) > 1 else "").expanduser().resolve()
    if not stack_dir.is_dir():
        print(f"error: stack dir not found: {stack_dir}", file=sys.stderr)
        return 1

    home = Path.home()
    codex_skills = home / ".agents" / "skills"
    codex_prompts = home / ".codex" / "prompts"
    codex_skills.mkdir(parents=True, exist_ok=True)
    codex_prompts.mkdir(parents=True, exist_ok=True)

    counts = {"skills": 0, "commands": 0, "skipped_skills": 0, "skipped_commands": 0}
    skip_dirs = {"commands", "scripts", "skills", ".git"}

    for skill_dir in sorted(stack_dir.iterdir()):
        if skill_dir.is_dir() and skill_dir.name not in skip_dirs:
            register_skill(skill_dir, stack_dir, codex_skills, counts)

    commands_dir = stack_dir / "commands"
    if commands_dir.is_dir():
        for command_file in sorted(commands_dir.glob("*.md")):
            register_command(command_file, stack_dir, codex_skills, codex_prompts, counts)

    print(
        f"Codex ({home / '.agents'}):",
        f"skills={counts['skills']}",
        f"commands={counts['commands']}",
        f"skipped_skills={counts['skipped_skills']}",
        f"skipped_commands={counts['skipped_commands']}",
        sep="\n  ",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())